### ISSUE TITLE
Envisionned toolset

### ISSUE THREAD

**Issue by sporniket** [sporniket/moto-tools#2]
* [ ] moto_tar : archive/extract files into/from k7 tape archives
* [ ] moto_fdar : same as moto_tar for floppy disk archives
* [ ] moto_bpp1 : Pretty printer for basic 1
* [ ] moto_bas2lst : Convert tokenized basic file into basic ascii listing
* [ ] moto_lst2bas : Convert basic ascii listing into tokenized basic
